#!/usr/bin/python
# -*- coding: iso-8859-1 -*-
# Copyright (C) 2008-2010 Bastian Kleineidam
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
"""
Check HTML pages for broken links. This is the GUI client.
"""
import sys
from PyQt4.QtGui import QApplication, QStyleFactory
from linkcheck.gui import LinkCheckerMain
from linkcheck import configuration, drop_privileges

## Look and feel with stylesheets
# In Cleanlooks the progress bar text is outside the bar.
# Use Plastique instead.
#Style = "Cleanlooks"
Style = "Plastique"

def main (argv=None):
    if argv is None:
        argv = sys.argv
    app = QApplication(argv)
    app.setApplicationName(configuration.AppName)
    app.setApplicationVersion(configuration.Version)
    app.setOrganizationName(configuration.Author)
    QApplication.setStyle(QStyleFactory.create(Style))
    QApplication.setPalette(QApplication.style().standardPalette())
    if app.argc() > 1:
        url = app.argv()[1]
    else:
        url = u""
    window = LinkCheckerMain(url=url)
    window.show()
    drop_privileges()
    sys.exit(app.exec_())


if __name__ == "__main__":
    main(argv=sys.argv)
