#!/usr/bin/python
# -*- coding: iso-8859-1 -*-
# Copyright (C) 2008-2009 Bastian Kleineidam
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
"""
Check HTML pages for broken links. This is the GUI client.
"""
import sys
from PyQt4.QtGui import QApplication
from linkchecker_main import LinkCheckerMain


def main (argv=None):
    if argv is None:
        argv = sys.argv
    if len(argv) > 1 and argv[1] in ("--version", "-V"):
        from linkcheck.director import console
        console.print_version()
        sys.exit(0)
    app = QApplication(argv)
    window = LinkCheckerMain()
    window.show()
    sys.exit(app.exec_())


if __name__ == "__main__":
    main(argv=sys.argv)
