# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created: Fri Feb 28 21:24:58 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(713, 627)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/app.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStatusTip(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setMargin(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(4, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.urlinput = LineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.urlinput.sizePolicy().hasHeightForWidth())
        self.urlinput.setSizePolicy(sizePolicy)
        self.urlinput.setMaxLength(2048)
        self.urlinput.setObjectName(_fromUtf8("urlinput"))
        self.horizontalLayout_3.addWidget(self.urlinput)
        spacerItem1 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.controlButton = QtGui.QPushButton(self.centralwidget)
        self.controlButton.setStatusTip(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/start.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.controlButton.setIcon(icon1)
        self.controlButton.setDefault(True)
        self.controlButton.setObjectName(_fromUtf8("controlButton"))
        self.horizontalLayout_3.addWidget(self.controlButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_29 = QtGui.QLabel(self.centralwidget)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_4.addWidget(self.label_29)
        self.label_32 = QtGui.QLabel(self.centralwidget)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_4.addWidget(self.label_32)
        self.label_active = QtGui.QLabel(self.centralwidget)
        self.label_active.setMinimumSize(QtCore.QSize(40, 0))
        self.label_active.setObjectName(_fromUtf8("label_active"))
        self.horizontalLayout_4.addWidget(self.label_active)
        self.label_30 = QtGui.QLabel(self.centralwidget)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_4.addWidget(self.label_30)
        self.label_queued = QtGui.QLabel(self.centralwidget)
        self.label_queued.setMinimumSize(QtCore.QSize(40, 0))
        self.label_queued.setObjectName(_fromUtf8("label_queued"))
        self.horizontalLayout_4.addWidget(self.label_queued)
        self.label_28 = QtGui.QLabel(self.centralwidget)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_4.addWidget(self.label_28)
        self.label_checked = QtGui.QLabel(self.centralwidget)
        self.label_checked.setMinimumSize(QtCore.QSize(50, 0))
        self.label_checked.setObjectName(_fromUtf8("label_checked"))
        self.horizontalLayout_4.addWidget(self.label_checked)
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_4.addWidget(self.label_15)
        self.label_busy = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(16)
        sizePolicy.setVerticalStretch(16)
        sizePolicy.setHeightForWidth(self.label_busy.sizePolicy().hasHeightForWidth())
        self.label_busy.setSizePolicy(sizePolicy)
        self.label_busy.setMinimumSize(QtCore.QSize(16, 16))
        self.label_busy.setObjectName(_fromUtf8("label_busy"))
        self.horizontalLayout_4.addWidget(self.label_busy)
        self.label_status = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_status.sizePolicy().hasHeightForWidth())
        self.label_status.setSizePolicy(sizePolicy)
        self.label_status.setText(_fromUtf8(""))
        self.label_status.setObjectName(_fromUtf8("label_status"))
        self.horizontalLayout_4.addWidget(self.label_status)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.treeView = QtGui.QTreeView(self.centralwidget)
        self.treeView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.treeView.setAlternatingRowColors(True)
        self.treeView.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.treeView.setRootIsDecorated(False)
        self.treeView.setUniformRowHeights(True)
        self.treeView.setItemsExpandable(False)
        self.treeView.setSortingEnabled(False)
        self.treeView.setAllColumnsShowFocus(True)
        self.treeView.setExpandsOnDoubleClick(False)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.verticalLayout.addWidget(self.treeView)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.url_properties = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.url_properties.sizePolicy().hasHeightForWidth())
        self.url_properties.setSizePolicy(sizePolicy)
        self.url_properties.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.url_properties.setObjectName(_fromUtf8("url_properties"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.url_properties)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.frame = QtGui.QFrame(self.url_properties)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.formLayout = QtGui.QFormLayout(self.frame)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.prop_url = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prop_url.sizePolicy().hasHeightForWidth())
        self.prop_url.setSizePolicy(sizePolicy)
        self.prop_url.setMinimumSize(QtCore.QSize(300, 0))
        self.prop_url.setFrameShape(QtGui.QFrame.StyledPanel)
        self.prop_url.setFrameShadow(QtGui.QFrame.Sunken)
        self.prop_url.setText(_fromUtf8(""))
        self.prop_url.setTextFormat(QtCore.Qt.RichText)
        self.prop_url.setOpenExternalLinks(True)
        self.prop_url.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.prop_url.setObjectName(_fromUtf8("prop_url"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.prop_url)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.prop_name = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prop_name.sizePolicy().hasHeightForWidth())
        self.prop_name.setSizePolicy(sizePolicy)
        self.prop_name.setMinimumSize(QtCore.QSize(300, 0))
        self.prop_name.setFrameShape(QtGui.QFrame.StyledPanel)
        self.prop_name.setFrameShadow(QtGui.QFrame.Sunken)
        self.prop_name.setText(_fromUtf8(""))
        self.prop_name.setTextFormat(QtCore.Qt.PlainText)
        self.prop_name.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.prop_name.setObjectName(_fromUtf8("prop_name"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.prop_name)
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.prop_parenturl = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prop_parenturl.sizePolicy().hasHeightForWidth())
        self.prop_parenturl.setSizePolicy(sizePolicy)
        self.prop_parenturl.setMinimumSize(QtCore.QSize(300, 0))
        self.prop_parenturl.setFrameShape(QtGui.QFrame.StyledPanel)
        self.prop_parenturl.setFrameShadow(QtGui.QFrame.Sunken)
        self.prop_parenturl.setText(_fromUtf8(""))
        self.prop_parenturl.setTextFormat(QtCore.Qt.RichText)
        self.prop_parenturl.setOpenExternalLinks(True)
        self.prop_parenturl.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.prop_parenturl.setObjectName(_fromUtf8("prop_parenturl"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.prop_parenturl)
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        self.prop_base = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prop_base.sizePolicy().hasHeightForWidth())
        self.prop_base.setSizePolicy(sizePolicy)
        self.prop_base.setMinimumSize(QtCore.QSize(300, 0))
        self.prop_base.setFrameShape(QtGui.QFrame.StyledPanel)
        self.prop_base.setFrameShadow(QtGui.QFrame.Sunken)
        self.prop_base.setText(_fromUtf8(""))
        self.prop_base.setTextFormat(QtCore.Qt.RichText)
        self.prop_base.setOpenExternalLinks(False)
        self.prop_base.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.prop_base.setObjectName(_fromUtf8("prop_base"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.prop_base)
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_7)
        self.prop_checktime = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prop_checktime.sizePolicy().hasHeightForWidth())
        self.prop_checktime.setSizePolicy(sizePolicy)
        self.prop_checktime.setMinimumSize(QtCore.QSize(300, 0))
        self.prop_checktime.setFrameShape(QtGui.QFrame.StyledPanel)
        self.prop_checktime.setFrameShadow(QtGui.QFrame.Sunken)
        self.prop_checktime.setText(_fromUtf8(""))
        self.prop_checktime.setTextFormat(QtCore.Qt.PlainText)
        self.prop_checktime.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.prop_checktime.setObjectName(_fromUtf8("prop_checktime"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.prop_checktime)
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_8)
        self.prop_dltime = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prop_dltime.sizePolicy().hasHeightForWidth())
        self.prop_dltime.setSizePolicy(sizePolicy)
        self.prop_dltime.setMinimumSize(QtCore.QSize(300, 0))
        self.prop_dltime.setFrameShape(QtGui.QFrame.StyledPanel)
        self.prop_dltime.setFrameShadow(QtGui.QFrame.Sunken)
        self.prop_dltime.setText(_fromUtf8(""))
        self.prop_dltime.setTextFormat(QtCore.Qt.PlainText)
        self.prop_dltime.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.prop_dltime.setObjectName(_fromUtf8("prop_dltime"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.prop_dltime)
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_9)
        self.prop_size = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prop_size.sizePolicy().hasHeightForWidth())
        self.prop_size.setSizePolicy(sizePolicy)
        self.prop_size.setMinimumSize(QtCore.QSize(300, 0))
        self.prop_size.setFrameShape(QtGui.QFrame.StyledPanel)
        self.prop_size.setFrameShadow(QtGui.QFrame.Sunken)
        self.prop_size.setText(_fromUtf8(""))
        self.prop_size.setTextFormat(QtCore.Qt.PlainText)
        self.prop_size.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.prop_size.setObjectName(_fromUtf8("prop_size"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.prop_size)
        self.label_10 = QtGui.QLabel(self.frame)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_10)
        self.prop_info = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prop_info.sizePolicy().hasHeightForWidth())
        self.prop_info.setSizePolicy(sizePolicy)
        self.prop_info.setMinimumSize(QtCore.QSize(300, 0))
        self.prop_info.setFrameShape(QtGui.QFrame.StyledPanel)
        self.prop_info.setFrameShadow(QtGui.QFrame.Sunken)
        self.prop_info.setText(_fromUtf8(""))
        self.prop_info.setTextFormat(QtCore.Qt.PlainText)
        self.prop_info.setWordWrap(True)
        self.prop_info.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.prop_info.setObjectName(_fromUtf8("prop_info"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.prop_info)
        self.label_11 = QtGui.QLabel(self.frame)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_11)
        self.prop_warning = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prop_warning.sizePolicy().hasHeightForWidth())
        self.prop_warning.setSizePolicy(sizePolicy)
        self.prop_warning.setMinimumSize(QtCore.QSize(300, 0))
        self.prop_warning.setFrameShape(QtGui.QFrame.StyledPanel)
        self.prop_warning.setFrameShadow(QtGui.QFrame.Sunken)
        self.prop_warning.setText(_fromUtf8(""))
        self.prop_warning.setTextFormat(QtCore.Qt.PlainText)
        self.prop_warning.setScaledContents(True)
        self.prop_warning.setWordWrap(True)
        self.prop_warning.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.prop_warning.setObjectName(_fromUtf8("prop_warning"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.prop_warning)
        self.label_12 = QtGui.QLabel(self.frame)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_12)
        self.prop_result = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prop_result.sizePolicy().hasHeightForWidth())
        self.prop_result.setSizePolicy(sizePolicy)
        self.prop_result.setMinimumSize(QtCore.QSize(300, 0))
        self.prop_result.setFrameShape(QtGui.QFrame.StyledPanel)
        self.prop_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.prop_result.setText(_fromUtf8(""))
        self.prop_result.setTextFormat(QtCore.Qt.PlainText)
        self.prop_result.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.prop_result.setObjectName(_fromUtf8("prop_result"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.prop_result)
        self.label_16 = QtGui.QLabel(self.frame)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_16)
        self.prop_modified = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prop_modified.sizePolicy().hasHeightForWidth())
        self.prop_modified.setSizePolicy(sizePolicy)
        self.prop_modified.setMinimumSize(QtCore.QSize(300, 0))
        self.prop_modified.setFrameShape(QtGui.QFrame.StyledPanel)
        self.prop_modified.setFrameShadow(QtGui.QFrame.Sunken)
        self.prop_modified.setText(_fromUtf8(""))
        self.prop_modified.setTextFormat(QtCore.Qt.PlainText)
        self.prop_modified.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.prop_modified.setObjectName(_fromUtf8("prop_modified"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.prop_modified)
        self.horizontalLayout_2.addWidget(self.frame)
        self.horizontalLayout.addWidget(self.url_properties)
        self.statistics = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statistics.sizePolicy().hasHeightForWidth())
        self.statistics.setSizePolicy(sizePolicy)
        self.statistics.setLineWidth(0)
        self.statistics.setObjectName(_fromUtf8("statistics"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.statistics)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.statistics)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_24 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout.addWidget(self.label_24, 0, 0, 1, 1)
        self.stats_valid_urls = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stats_valid_urls.sizePolicy().hasHeightForWidth())
        self.stats_valid_urls.setSizePolicy(sizePolicy)
        self.stats_valid_urls.setMinimumSize(QtCore.QSize(30, 0))
        self.stats_valid_urls.setFrameShape(QtGui.QFrame.StyledPanel)
        self.stats_valid_urls.setFrameShadow(QtGui.QFrame.Sunken)
        self.stats_valid_urls.setText(_fromUtf8(""))
        self.stats_valid_urls.setTextFormat(QtCore.Qt.RichText)
        self.stats_valid_urls.setOpenExternalLinks(True)
        self.stats_valid_urls.setObjectName(_fromUtf8("stats_valid_urls"))
        self.gridLayout.addWidget(self.stats_valid_urls, 0, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout.addWidget(self.label_26, 0, 2, 1, 1)
        self.stats_warnings = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stats_warnings.sizePolicy().hasHeightForWidth())
        self.stats_warnings.setSizePolicy(sizePolicy)
        self.stats_warnings.setMinimumSize(QtCore.QSize(30, 0))
        self.stats_warnings.setFrameShape(QtGui.QFrame.StyledPanel)
        self.stats_warnings.setFrameShadow(QtGui.QFrame.Sunken)
        self.stats_warnings.setText(_fromUtf8(""))
        self.stats_warnings.setTextFormat(QtCore.Qt.RichText)
        self.stats_warnings.setOpenExternalLinks(True)
        self.stats_warnings.setObjectName(_fromUtf8("stats_warnings"))
        self.gridLayout.addWidget(self.stats_warnings, 0, 3, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout.addWidget(self.label_25, 1, 0, 1, 1)
        self.stats_invalid_urls = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stats_invalid_urls.sizePolicy().hasHeightForWidth())
        self.stats_invalid_urls.setSizePolicy(sizePolicy)
        self.stats_invalid_urls.setMinimumSize(QtCore.QSize(30, 0))
        self.stats_invalid_urls.setFrameShape(QtGui.QFrame.StyledPanel)
        self.stats_invalid_urls.setFrameShadow(QtGui.QFrame.Sunken)
        self.stats_invalid_urls.setText(_fromUtf8(""))
        self.stats_invalid_urls.setTextFormat(QtCore.Qt.RichText)
        self.stats_invalid_urls.setOpenExternalLinks(True)
        self.stats_invalid_urls.setObjectName(_fromUtf8("stats_invalid_urls"))
        self.gridLayout.addWidget(self.stats_invalid_urls, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(self.statistics)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.stats_content_image = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stats_content_image.sizePolicy().hasHeightForWidth())
        self.stats_content_image.setSizePolicy(sizePolicy)
        self.stats_content_image.setMinimumSize(QtCore.QSize(40, 0))
        self.stats_content_image.setFrameShape(QtGui.QFrame.StyledPanel)
        self.stats_content_image.setFrameShadow(QtGui.QFrame.Sunken)
        self.stats_content_image.setText(_fromUtf8(""))
        self.stats_content_image.setTextFormat(QtCore.Qt.RichText)
        self.stats_content_image.setOpenExternalLinks(True)
        self.stats_content_image.setObjectName(_fromUtf8("stats_content_image"))
        self.gridLayout_2.addWidget(self.stats_content_image, 0, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 0, 2, 1, 1)
        self.stats_content_text = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stats_content_text.sizePolicy().hasHeightForWidth())
        self.stats_content_text.setSizePolicy(sizePolicy)
        self.stats_content_text.setMinimumSize(QtCore.QSize(40, 0))
        self.stats_content_text.setFrameShape(QtGui.QFrame.StyledPanel)
        self.stats_content_text.setFrameShadow(QtGui.QFrame.Sunken)
        self.stats_content_text.setText(_fromUtf8(""))
        self.stats_content_text.setTextFormat(QtCore.Qt.RichText)
        self.stats_content_text.setOpenExternalLinks(True)
        self.stats_content_text.setObjectName(_fromUtf8("stats_content_text"))
        self.gridLayout_2.addWidget(self.stats_content_text, 0, 3, 1, 1)
        self.label_27 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_2.addWidget(self.label_27, 0, 4, 1, 1)
        self.stats_content_application = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stats_content_application.sizePolicy().hasHeightForWidth())
        self.stats_content_application.setSizePolicy(sizePolicy)
        self.stats_content_application.setMinimumSize(QtCore.QSize(40, 0))
        self.stats_content_application.setFrameShape(QtGui.QFrame.StyledPanel)
        self.stats_content_application.setFrameShadow(QtGui.QFrame.Sunken)
        self.stats_content_application.setText(_fromUtf8(""))
        self.stats_content_application.setTextFormat(QtCore.Qt.RichText)
        self.stats_content_application.setOpenExternalLinks(True)
        self.stats_content_application.setObjectName(_fromUtf8("stats_content_application"))
        self.gridLayout_2.addWidget(self.stats_content_application, 0, 5, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 1, 0, 1, 1)
        self.stats_content_audio = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stats_content_audio.sizePolicy().hasHeightForWidth())
        self.stats_content_audio.setSizePolicy(sizePolicy)
        self.stats_content_audio.setMinimumSize(QtCore.QSize(40, 0))
        self.stats_content_audio.setFrameShape(QtGui.QFrame.StyledPanel)
        self.stats_content_audio.setFrameShadow(QtGui.QFrame.Sunken)
        self.stats_content_audio.setText(_fromUtf8(""))
        self.stats_content_audio.setTextFormat(QtCore.Qt.RichText)
        self.stats_content_audio.setOpenExternalLinks(True)
        self.stats_content_audio.setObjectName(_fromUtf8("stats_content_audio"))
        self.gridLayout_2.addWidget(self.stats_content_audio, 1, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 1, 2, 1, 1)
        self.stats_content_video = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stats_content_video.sizePolicy().hasHeightForWidth())
        self.stats_content_video.setSizePolicy(sizePolicy)
        self.stats_content_video.setMinimumSize(QtCore.QSize(40, 0))
        self.stats_content_video.setFrameShape(QtGui.QFrame.StyledPanel)
        self.stats_content_video.setFrameShadow(QtGui.QFrame.Sunken)
        self.stats_content_video.setText(_fromUtf8(""))
        self.stats_content_video.setTextFormat(QtCore.Qt.RichText)
        self.stats_content_video.setOpenExternalLinks(True)
        self.stats_content_video.setObjectName(_fromUtf8("stats_content_video"))
        self.gridLayout_2.addWidget(self.stats_content_video, 1, 3, 1, 1)
        self.stats_content_other = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stats_content_other.sizePolicy().hasHeightForWidth())
        self.stats_content_other.setSizePolicy(sizePolicy)
        self.stats_content_other.setMinimumSize(QtCore.QSize(40, 0))
        self.stats_content_other.setFrameShape(QtGui.QFrame.StyledPanel)
        self.stats_content_other.setFrameShadow(QtGui.QFrame.Sunken)
        self.stats_content_other.setText(_fromUtf8(""))
        self.stats_content_other.setTextFormat(QtCore.Qt.RichText)
        self.stats_content_other.setOpenExternalLinks(True)
        self.stats_content_other.setObjectName(_fromUtf8("stats_content_other"))
        self.gridLayout_2.addWidget(self.stats_content_other, 2, 5, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_2.addWidget(self.label_23, 2, 4, 1, 1)
        self.stats_content_mail = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stats_content_mail.sizePolicy().hasHeightForWidth())
        self.stats_content_mail.setSizePolicy(sizePolicy)
        self.stats_content_mail.setMinimumSize(QtCore.QSize(40, 0))
        self.stats_content_mail.setFrameShape(QtGui.QFrame.StyledPanel)
        self.stats_content_mail.setFrameShadow(QtGui.QFrame.Sunken)
        self.stats_content_mail.setText(_fromUtf8(""))
        self.stats_content_mail.setTextFormat(QtCore.Qt.RichText)
        self.stats_content_mail.setOpenExternalLinks(True)
        self.stats_content_mail.setObjectName(_fromUtf8("stats_content_mail"))
        self.gridLayout_2.addWidget(self.stats_content_mail, 1, 5, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_2.addWidget(self.label_22, 1, 4, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(self.statistics)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_18 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_3.addWidget(self.label_18, 0, 0, 1, 1)
        self.stats_url_minlen = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stats_url_minlen.sizePolicy().hasHeightForWidth())
        self.stats_url_minlen.setSizePolicy(sizePolicy)
        self.stats_url_minlen.setMinimumSize(QtCore.QSize(30, 0))
        self.stats_url_minlen.setFrameShape(QtGui.QFrame.StyledPanel)
        self.stats_url_minlen.setFrameShadow(QtGui.QFrame.Sunken)
        self.stats_url_minlen.setText(_fromUtf8(""))
        self.stats_url_minlen.setTextFormat(QtCore.Qt.RichText)
        self.stats_url_minlen.setOpenExternalLinks(True)
        self.stats_url_minlen.setObjectName(_fromUtf8("stats_url_minlen"))
        self.gridLayout_3.addWidget(self.stats_url_minlen, 0, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_3.addWidget(self.label_20, 0, 2, 1, 1)
        self.stats_url_avglen = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stats_url_avglen.sizePolicy().hasHeightForWidth())
        self.stats_url_avglen.setSizePolicy(sizePolicy)
        self.stats_url_avglen.setMinimumSize(QtCore.QSize(30, 0))
        self.stats_url_avglen.setFrameShape(QtGui.QFrame.StyledPanel)
        self.stats_url_avglen.setFrameShadow(QtGui.QFrame.Sunken)
        self.stats_url_avglen.setText(_fromUtf8(""))
        self.stats_url_avglen.setTextFormat(QtCore.Qt.RichText)
        self.stats_url_avglen.setOpenExternalLinks(True)
        self.stats_url_avglen.setObjectName(_fromUtf8("stats_url_avglen"))
        self.gridLayout_3.addWidget(self.stats_url_avglen, 0, 3, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_3.addWidget(self.label_19, 1, 0, 1, 1)
        self.stats_url_maxlen = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stats_url_maxlen.sizePolicy().hasHeightForWidth())
        self.stats_url_maxlen.setSizePolicy(sizePolicy)
        self.stats_url_maxlen.setMinimumSize(QtCore.QSize(30, 0))
        self.stats_url_maxlen.setFrameShape(QtGui.QFrame.StyledPanel)
        self.stats_url_maxlen.setFrameShadow(QtGui.QFrame.Sunken)
        self.stats_url_maxlen.setText(_fromUtf8(""))
        self.stats_url_maxlen.setTextFormat(QtCore.Qt.RichText)
        self.stats_url_maxlen.setOpenExternalLinks(True)
        self.stats_url_maxlen.setObjectName(_fromUtf8("stats_url_maxlen"))
        self.gridLayout_3.addWidget(self.stats_url_maxlen, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.horizontalLayout.addWidget(self.statistics)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 713, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionAbout = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/about.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon2)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionHelp = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/help.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon3)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionViewOnline = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/online.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionViewOnline.setIcon(icon4)
        self.actionViewOnline.setObjectName(_fromUtf8("actionViewOnline"))
        self.actionOptions = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/preferences.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOptions.setIcon(icon5)
        self.actionOptions.setObjectName(_fromUtf8("actionOptions"))
        self.actionCopyToClipboard = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/copy.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopyToClipboard.setIcon(icon6)
        self.actionCopyToClipboard.setObjectName(_fromUtf8("actionCopyToClipboard"))
        self.actionViewParentOnline = QtGui.QAction(MainWindow)
        self.actionViewParentOnline.setIcon(icon4)
        self.actionViewParentOnline.setObjectName(_fromUtf8("actionViewParentOnline"))
        self.actionViewParentSource = QtGui.QAction(MainWindow)
        self.actionViewParentSource.setIcon(icon4)
        self.actionViewParentSource.setObjectName(_fromUtf8("actionViewParentSource"))
        self.actionDebug = QtGui.QAction(MainWindow)
        self.actionDebug.setObjectName(_fromUtf8("actionDebug"))
        self.actionViewProperties = QtGui.QAction(MainWindow)
        self.actionViewProperties.setObjectName(_fromUtf8("actionViewProperties"))
        self.actionSave = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon7)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionQuit = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon8)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionCheckUpdates = QtGui.QAction(MainWindow)
        self.actionCheckUpdates.setObjectName(_fromUtf8("actionCheckUpdates"))
        self.actionDonate = QtGui.QAction(MainWindow)
        self.actionDonate.setObjectName(_fromUtf8("actionDonate"))
        self.actionOpen_project = QtGui.QAction(MainWindow)
        self.actionOpen_project.setObjectName(_fromUtf8("actionOpen_project"))
        self.actionSave_project = QtGui.QAction(MainWindow)
        self.actionSave_project.setObjectName(_fromUtf8("actionSave_project"))
        self.menuEdit.addAction(self.actionOptions)
        self.menuFile.addAction(self.actionOpen_project)
        self.menuFile.addAction(self.actionSave_project)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionDebug)
        self.menuHelp.addAction(self.actionCheckUpdates)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.label.setBuddy(self.urlinput)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_("LinkChecker"))
        self.label.setText(_("URL:"))
        self.controlButton.setToolTip(_("Start checking the given URL."))
        self.controlButton.setText(QtGui.QApplication.translate("MainWindow", "Start", "Start checking URL", QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(_("URLs: "))
        self.label_32.setText(_("active"))
        self.label_active.setText(_("0"))
        self.label_30.setText(_("queued"))
        self.label_queued.setText(_("0"))
        self.label_28.setText(_("checked"))
        self.label_checked.setText(_("0"))
        self.label_15.setText(_("Info:"))
        self.label_busy.setText(_("-"))
        self.url_properties.setTitle(_("URL properties"))
        self.label_2.setText(_("URL"))
        self.label_3.setText(_("Name"))
        self.label_4.setText(_("Parent URL"))
        self.label_5.setText(_("Base"))
        self.label_7.setText(_("Check time"))
        self.label_8.setText(_("D/L time"))
        self.label_9.setText(_("Size"))
        self.label_10.setText(_("Info"))
        self.label_11.setText(_("Warning"))
        self.label_12.setText(_("Result"))
        self.label_16.setText(_("Modified"))
        self.groupBox.setTitle(_("Check results"))
        self.label_24.setText(_("Valid URLs"))
        self.label_26.setText(_("Warnings"))
        self.label_25.setText(_("Invalid URLs"))
        self.groupBox_3.setTitle(_("Content type statistics"))
        self.label_6.setText(_("Image"))
        self.label_13.setText(_("Text"))
        self.label_27.setText(_("Application"))
        self.label_17.setText(_("Audio"))
        self.label_21.setText(_("Video"))
        self.label_23.setText(_("Other"))
        self.label_22.setText(_("Mail"))
        self.groupBox_2.setTitle(_("URL statistics"))
        self.label_18.setText(_("Min. length"))
        self.label_20.setText(_("Avg. length"))
        self.label_19.setText(_("Max. length"))
        self.menuEdit.setTitle(_("&Edit"))
        self.menuFile.setTitle(_("&File"))
        self.menuHelp.setTitle(_("&Help"))
        self.actionAbout.setText(_("A&bout"))
        self.actionAbout.setIconText(_("About"))
        self.actionHelp.setText(_("&Help"))
        self.actionHelp.setIconText(_("Help"))
        self.actionViewOnline.setText(_("View online"))
        self.actionViewOnline.setToolTip(_("View URL online"))
        self.actionOptions.setText(_("&Options"))
        self.actionOptions.setIconText(_("Options"))
        self.actionCopyToClipboard.setText(_("Copy to clipboard"))
        self.actionCopyToClipboard.setToolTip(_("Copy URL to clipboard"))
        self.actionCopyToClipboard.setShortcut(_("Ctrl+C"))
        self.actionViewParentOnline.setText(_("View parent online"))
        self.actionViewParentOnline.setToolTip(_("View parent URL online"))
        self.actionViewParentSource.setText(_("View parent source"))
        self.actionViewParentSource.setToolTip(_("View parent URL source"))
        self.actionDebug.setText(_("Show debug"))
        self.actionViewProperties.setText(_("View properties"))
        self.actionViewProperties.setToolTip(_("View URL properties"))
        self.actionSave.setText(_("Save &results..."))
        self.actionQuit.setText(_("&Quit"))
        self.actionQuit.setShortcut(_("Ctrl+Q"))
        self.actionCheckUpdates.setText(_("Check for updates"))
        self.actionDonate.setText(_("Donate"))
        self.actionOpen_project.setText(_("&Open project..."))
        self.actionOpen_project.setIconText(_("Open project"))
        self.actionOpen_project.setShortcut(_("Ctrl+O"))
        self.actionSave_project.setText(_("&Save project..."))
        self.actionSave_project.setShortcut(_("Ctrl+S"))

from lineedit import LineEdit
import linkchecker_rc
