# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/properties.ui'
#
# Created: Sat Nov  6 11:31:30 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_PropertiesDialog(object):
    def setupUi(self, PropertiesDialog):
        PropertiesDialog.setObjectName("PropertiesDialog")
        PropertiesDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        PropertiesDialog.resize(466, 315)
        self.verticalLayout = QtGui.QVBoxLayout(PropertiesDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtGui.QFrame(PropertiesDialog)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtGui.QFormLayout(self.frame)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.prop_id = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prop_id.sizePolicy().hasHeightForWidth())
        self.prop_id.setSizePolicy(sizePolicy)
        self.prop_id.setFrameShape(QtGui.QFrame.StyledPanel)
        self.prop_id.setFrameShadow(QtGui.QFrame.Sunken)
        self.prop_id.setText("")
        self.prop_id.setTextFormat(QtCore.Qt.PlainText)
        self.prop_id.setObjectName("prop_id")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.prop_id)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.prop_url = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prop_url.sizePolicy().hasHeightForWidth())
        self.prop_url.setSizePolicy(sizePolicy)
        self.prop_url.setFrameShape(QtGui.QFrame.StyledPanel)
        self.prop_url.setFrameShadow(QtGui.QFrame.Sunken)
        self.prop_url.setText("")
        self.prop_url.setTextFormat(QtCore.Qt.RichText)
        self.prop_url.setObjectName("prop_url")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.prop_url)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.prop_name = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prop_name.sizePolicy().hasHeightForWidth())
        self.prop_name.setSizePolicy(sizePolicy)
        self.prop_name.setFrameShape(QtGui.QFrame.StyledPanel)
        self.prop_name.setFrameShadow(QtGui.QFrame.Sunken)
        self.prop_name.setText("")
        self.prop_name.setTextFormat(QtCore.Qt.PlainText)
        self.prop_name.setObjectName("prop_name")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.prop_name)
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.prop_parenturl = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prop_parenturl.sizePolicy().hasHeightForWidth())
        self.prop_parenturl.setSizePolicy(sizePolicy)
        self.prop_parenturl.setFrameShape(QtGui.QFrame.StyledPanel)
        self.prop_parenturl.setFrameShadow(QtGui.QFrame.Sunken)
        self.prop_parenturl.setText("")
        self.prop_parenturl.setTextFormat(QtCore.Qt.RichText)
        self.prop_parenturl.setObjectName("prop_parenturl")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.prop_parenturl)
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.prop_base = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prop_base.sizePolicy().hasHeightForWidth())
        self.prop_base.setSizePolicy(sizePolicy)
        self.prop_base.setFrameShape(QtGui.QFrame.StyledPanel)
        self.prop_base.setFrameShadow(QtGui.QFrame.Sunken)
        self.prop_base.setText("")
        self.prop_base.setTextFormat(QtCore.Qt.RichText)
        self.prop_base.setObjectName("prop_base")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.prop_base)
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_7)
        self.prop_checktime = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prop_checktime.sizePolicy().hasHeightForWidth())
        self.prop_checktime.setSizePolicy(sizePolicy)
        self.prop_checktime.setFrameShape(QtGui.QFrame.StyledPanel)
        self.prop_checktime.setFrameShadow(QtGui.QFrame.Sunken)
        self.prop_checktime.setText("")
        self.prop_checktime.setTextFormat(QtCore.Qt.PlainText)
        self.prop_checktime.setObjectName("prop_checktime")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.prop_checktime)
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_8)
        self.prop_dltime = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prop_dltime.sizePolicy().hasHeightForWidth())
        self.prop_dltime.setSizePolicy(sizePolicy)
        self.prop_dltime.setFrameShape(QtGui.QFrame.StyledPanel)
        self.prop_dltime.setFrameShadow(QtGui.QFrame.Sunken)
        self.prop_dltime.setText("")
        self.prop_dltime.setTextFormat(QtCore.Qt.PlainText)
        self.prop_dltime.setObjectName("prop_dltime")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.prop_dltime)
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_9)
        self.prop_size = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prop_size.sizePolicy().hasHeightForWidth())
        self.prop_size.setSizePolicy(sizePolicy)
        self.prop_size.setFrameShape(QtGui.QFrame.StyledPanel)
        self.prop_size.setFrameShadow(QtGui.QFrame.Sunken)
        self.prop_size.setText("")
        self.prop_size.setTextFormat(QtCore.Qt.PlainText)
        self.prop_size.setObjectName("prop_size")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.prop_size)
        self.label_10 = QtGui.QLabel(self.frame)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_10)
        self.prop_info = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prop_info.sizePolicy().hasHeightForWidth())
        self.prop_info.setSizePolicy(sizePolicy)
        self.prop_info.setFrameShape(QtGui.QFrame.StyledPanel)
        self.prop_info.setFrameShadow(QtGui.QFrame.Sunken)
        self.prop_info.setText("")
        self.prop_info.setTextFormat(QtCore.Qt.PlainText)
        self.prop_info.setWordWrap(True)
        self.prop_info.setObjectName("prop_info")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.prop_info)
        self.label_11 = QtGui.QLabel(self.frame)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_11)
        self.prop_warning = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prop_warning.sizePolicy().hasHeightForWidth())
        self.prop_warning.setSizePolicy(sizePolicy)
        self.prop_warning.setFrameShape(QtGui.QFrame.StyledPanel)
        self.prop_warning.setFrameShadow(QtGui.QFrame.Sunken)
        self.prop_warning.setText("")
        self.prop_warning.setTextFormat(QtCore.Qt.PlainText)
        self.prop_warning.setScaledContents(True)
        self.prop_warning.setWordWrap(True)
        self.prop_warning.setObjectName("prop_warning")
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.prop_warning)
        self.label_12 = QtGui.QLabel(self.frame)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_12)
        self.prop_result = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prop_result.sizePolicy().hasHeightForWidth())
        self.prop_result.setSizePolicy(sizePolicy)
        self.prop_result.setFrameShape(QtGui.QFrame.StyledPanel)
        self.prop_result.setFrameShadow(QtGui.QFrame.Sunken)
        self.prop_result.setText("")
        self.prop_result.setTextFormat(QtCore.Qt.PlainText)
        self.prop_result.setObjectName("prop_result")
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.prop_result)
        self.verticalLayout.addWidget(self.frame)
        self.okButton = QtGui.QPushButton(PropertiesDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okButton.sizePolicy().hasHeightForWidth())
        self.okButton.setSizePolicy(sizePolicy)
        self.okButton.setObjectName("okButton")
        self.verticalLayout.addWidget(self.okButton)

        self.retranslateUi(PropertiesDialog)
        QtCore.QMetaObject.connectSlotsByName(PropertiesDialog)

    def retranslateUi(self, PropertiesDialog):
        PropertiesDialog.setWindowTitle(_("LinkChecker URL properties"))
        self.label.setText(_("ID"))
        self.label_2.setText(_("URL"))
        self.label_3.setText(_("Name"))
        self.label_4.setText(_("Parent URL"))
        self.label_5.setText(_("Base"))
        self.label_7.setText(_("Check time"))
        self.label_8.setText(_("D/L time"))
        self.label_9.setText(_("Size"))
        self.label_10.setText(_("Info"))
        self.label_11.setText(_("Warning"))
        self.label_12.setText(_("Result"))
        self.okButton.setText(_("Ok"))

