# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/options.ui'
#
# Created: Fri Dec 16 21:48:49 2011
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Options(object):
    def setupUi(self, Options):
        Options.setObjectName(_fromUtf8("Options"))
        Options.resize(455, 550)
        Options.setMinimumSize(QtCore.QSize(400, 550))
        Options.setWindowTitle(_("Dialog"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(Options)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(Options)
        self.groupBox_2.setTitle(_("Checking options"))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.widget = QtGui.QWidget(self.groupBox_2)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.formLayout = QtGui.QFormLayout(self.widget)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setToolTip(_("Check recursively all links up to given depth. A negative depth will enable infinite recursion."))
        self.label.setText(_("Recursive depth"))
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.recursionlevel = QtGui.QSpinBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recursionlevel.sizePolicy().hasHeightForWidth())
        self.recursionlevel.setSizePolicy(sizePolicy)
        self.recursionlevel.setMinimumSize(QtCore.QSize(0, 25))
        self.recursionlevel.setToolTip(_("Check recursively all links up to given depth. A negative depth will enable infinite recursion."))
        self.recursionlevel.setMinimum(-1)
        self.recursionlevel.setMaximum(100)
        self.recursionlevel.setProperty("value", -1)
        self.recursionlevel.setObjectName(_fromUtf8("recursionlevel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.recursionlevel)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setToolTip(_("Log all checked URLs once. Default is to log only errors and warnings."))
        self.label_2.setText(_("Verbose output"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.verbose = QtGui.QCheckBox(self.widget)
        self.verbose.setEnabled(True)
        self.verbose.setToolTip(_("Log all checked URLs once. Default is to log only errors and warnings."))
        self.verbose.setText(_fromUtf8(""))
        self.verbose.setObjectName(_fromUtf8("verbose"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.verbose)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setText(_("Debug"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.debug = QtGui.QCheckBox(self.widget)
        self.debug.setText(_fromUtf8(""))
        self.debug.setObjectName(_fromUtf8("debug"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.debug)
        self.verticalLayout.addWidget(self.widget)
        spacerItem = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setText(_("Warn when one of these strings are found (one per line):"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.warninglines = QtGui.QPlainTextEdit(self.groupBox_2)
        self.warninglines.setMaximumSize(QtCore.QSize(16777215, 150))
        self.warninglines.setObjectName(_fromUtf8("warninglines"))
        self.verticalLayout.addWidget(self.warninglines)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setText(_("Ignore URLs matching one of these patterns (one per line):"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        self.ignorelines = QtGui.QPlainTextEdit(self.groupBox_2)
        self.ignorelines.setMaximumSize(QtCore.QSize(16777215, 150))
        self.ignorelines.setObjectName(_fromUtf8("ignorelines"))
        self.verticalLayout.addWidget(self.ignorelines)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(Options)
        self.groupBox.setTitle(_("Configuration file"))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setText(_("The configuration file holds advanced options and can be edited with an integrated text editor."))
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.user_config_label_2 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_config_label_2.sizePolicy().hasHeightForWidth())
        self.user_config_label_2.setSizePolicy(sizePolicy)
        self.user_config_label_2.setToolTip(_("Overrides system wide configuration file settings."))
        self.user_config_label_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.user_config_label_2.setLineWidth(0)
        self.user_config_label_2.setText(_("/home/user/.linkchecker/linkcheckerrc"))
        self.user_config_label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.user_config_label_2.setWordWrap(True)
        self.user_config_label_2.setMargin(0)
        self.user_config_label_2.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.user_config_label_2.setObjectName(_fromUtf8("user_config_label_2"))
        self.verticalLayout_2.addWidget(self.user_config_label_2)
        self.user_config_button = QtGui.QPushButton(self.groupBox)
        self.user_config_button.setEnabled(False)
        self.user_config_button.setToolTip(_fromUtf8(""))
        self.user_config_button.setText(_("Edit"))
        self.user_config_button.setObjectName(_fromUtf8("user_config_button"))
        self.verticalLayout_2.addWidget(self.user_config_button)
        self.verticalLayout_3.addWidget(self.groupBox)
        spacerItem2 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.widget_2 = QtGui.QWidget(Options)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.closeButton = QtGui.QPushButton(self.widget_2)
        self.closeButton.setText(_("Close"))
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.horizontalLayout.addWidget(self.closeButton)
        spacerItem3 = QtGui.QSpacerItem(317, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_3.addWidget(self.widget_2)

        self.retranslateUi(Options)
        QtCore.QMetaObject.connectSlotsByName(Options)

    def retranslateUi(self, Options):
        pass

