#!/bin/sh -e
#
# Written 1998 by Gregor Hoffleit <flight@debian.org>.
# used by Bastian Kleineidam for LinkChecker

PACKAGE=linkchecker
PYTHON=python2.1

#DEBHELPER#

dpkg --listfiles $PACKAGE |
        awk '$0~/\.py$/ {print $0"c\n" $0"o"}' |
        xargs rm -f >&2

rmdir /usr/lib/$PYTHON/site-packages/linkcheck 2>/dev/null || true
rmdir /usr/lib/$PYTHON/site-packages/DNS 2>/dev/null || true

exit 0
