#! /bin/sh
#
# Written 1998 by Gregor Hoffleit <flight@debian.org>.
# used by Bastian Kleineidam for LinkChecker

set -e

PACKAGE=linkchecker

dpkg --listfiles $PACKAGE |
        awk '$0~/\.py$/ {print $0"c\n" $0"o"}' |
        xargs rm -f >&2

rmdir /usr/lib/python1.5/site-packages/linkcheck 2>/dev/null || true

#DEBHELPER#

exit 0
