.TH LINKCHECKER-GUI 1 2009-01-10 "LinkChecker GUI" "LinkChecker GUI client"
.SH NAME
linkchecker-gui - GUI client to check links of websites and HTML documents
.
.SH SYNOPSIS
\fBlinkchecker-gui\fP
.
.SH DESCRIPTION
A graphical interface to check links of websites and HTML documents.

.SH "SEE ALSO"
\fBlinkchecker\fP(1)
.
.SH AUTHOR
Bastian Kleineidam <calvin@users.sourceforge.net>
.
.SH COPYRIGHT
Copyright \(co 2009-2010 Bastian Kleineidam
